<?php
/**
 * Database schema definitions.
 *
 * @package Omnify
 */

namespace Omnify\eCommerce\Database;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
use wpdb;

class Omnify_Schema {
	public function table(string $omnify_name): string {
		global $wpdb;

		return $wpdb->prefix . 'omnify_' . $omnify_name;
	}

	/**
	 * @return array<string, string>
	 */
	public function statements(): array {
		global $wpdb;

		$omnify_charset = $wpdb->get_charset_collate();

		return [
			'migrations' => "CREATE TABLE {$this->table('migrations')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				migration VARCHAR(190) NOT NULL,
				ran_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY migration (migration)
			) {$omnify_charset};",
			'products'   => "CREATE TABLE {$this->table('products')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				status VARCHAR(32) NOT NULL DEFAULT 'draft',
				type VARCHAR(32) NOT NULL DEFAULT 'download',
				name VARCHAR(190) NOT NULL,
				slug VARCHAR(190) NOT NULL,
				description LONGTEXT NULL,
				short_description TEXT NULL,
				thumbnail_id BIGINT UNSIGNED NULL,
				price DECIMAL(18,6) NOT NULL DEFAULT 0,
				sale_price DECIMAL(18,6) NULL,
				currency CHAR(3) NOT NULL DEFAULT 'USD',
				sku VARCHAR(100) NULL,
				manage_stock TINYINT NOT NULL DEFAULT 0,
				stock_qty INT NULL DEFAULT 0,
				stock_status VARCHAR(32) NOT NULL DEFAULT 'instock',
				deleted_at DATETIME NULL,
				allow_backorders TINYINT NOT NULL DEFAULT 0,
				preorder_enabled TINYINT NOT NULL DEFAULT 0,
				preorder_release_date DATE NULL,
				preorder_limit INT UNSIGNED NULL DEFAULT NULL,
				preorder_message VARCHAR(255) NULL,
				weight DECIMAL(10,2) NULL,
				length DECIMAL(10,2) NULL,
				width DECIMAL(10,2) NULL,
				height DECIMAL(10,2) NULL,
				shipping_class VARCHAR(120) NULL,
				attributes LONGTEXT NULL,
				variation_settings LONGTEXT NULL,
				specifications LONGTEXT NULL,
				delivery_info TEXT NULL,
				return_info TEXT NULL,
				gallery_ids LONGTEXT NULL,
				video_url VARCHAR(500) NULL,
				video_poster_url VARCHAR(500) NULL,
				trust_badge_title VARCHAR(160) NULL,
				trust_badge_text TEXT NULL,
				download_expiry_days INT UNSIGNED NULL DEFAULT 0,
				max_purchase_qty INT UNSIGNED NULL DEFAULT NULL,
				bundled_ids TEXT NULL,
				upsell_ids TEXT NULL,
				cross_sell_ids TEXT NULL,
				refund_enabled TINYINT NOT NULL DEFAULT 1,
				refund_window_days INT UNSIGNED NULL DEFAULT NULL,
				refund_policy_text TEXT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY slug (slug),
				KEY status_type (status, type)
			) {$omnify_charset};",
			'product_variations' => "CREATE TABLE {$this->table('product_variations')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				sku VARCHAR(100) NULL,
				price DECIMAL(18,6) NOT NULL DEFAULT 0,
				sale_price DECIMAL(18,6) NULL,
				attributes TEXT NOT NULL,
				description TEXT NULL,
				manage_stock TINYINT NOT NULL DEFAULT 0,
				stock_qty INT NULL DEFAULT 0,
				stock_status VARCHAR(32) NOT NULL DEFAULT 'instock',
				allow_backorders TINYINT NOT NULL DEFAULT 0,
				preorder_enabled TINYINT NOT NULL DEFAULT 0,
				preorder_release_date DATE NULL,
				preorder_limit INT UNSIGNED NULL DEFAULT NULL,
				preorder_message VARCHAR(255) NULL,
				thumbnail_id BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id)
			) {$omnify_charset};",
			'product_categories' => "CREATE TABLE {$this->table('product_categories')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				name VARCHAR(120) NOT NULL,
				slug VARCHAR(140) NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY slug (slug)
			) {$omnify_charset};",
			'product_tags' => "CREATE TABLE {$this->table('product_tags')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				name VARCHAR(120) NOT NULL,
				slug VARCHAR(140) NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY slug (slug)
			) {$omnify_charset};",
			'product_brands' => "CREATE TABLE {$this->table('product_brands')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				name VARCHAR(120) NOT NULL,
				slug VARCHAR(140) NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY slug (slug)
			) {$omnify_charset};",
			'product_files' => "CREATE TABLE {$this->table('product_files')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				attachment_id BIGINT UNSIGNED NULL,
				version VARCHAR(80) NOT NULL DEFAULT '1.0.0',
				file_name VARCHAR(190) NOT NULL,
				file_path TEXT NOT NULL,
				file_url TEXT NULL,
				file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
				file_type VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
				expires_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY expires_at (expires_at),
				KEY product_version (product_id, version)
			) {$omnify_charset};",
			'customers'  => "CREATE TABLE {$this->table('customers')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				user_id BIGINT UNSIGNED NULL,
				email VARCHAR(190) NOT NULL,
				first_name VARCHAR(100) NULL,
				last_name VARCHAR(100) NULL,
				phone VARCHAR(60) NULL,
				company VARCHAR(160) NULL,
				country CHAR(2) NULL,
				shipping_first_name VARCHAR(100) NULL,
				shipping_last_name VARCHAR(100) NULL,
				shipping_phone VARCHAR(60) NULL,
				shipping_company VARCHAR(160) NULL,
				shipping_address_1 VARCHAR(190) NULL,
				shipping_address_2 VARCHAR(190) NULL,
				shipping_city VARCHAR(100) NULL,
				shipping_state VARCHAR(100) NULL,
				shipping_postcode VARCHAR(20) NULL,
				shipping_country CHAR(2) NULL,
				billing_first_name VARCHAR(100) NULL,
				billing_last_name VARCHAR(100) NULL,
				billing_phone VARCHAR(60) NULL,
				billing_company VARCHAR(160) NULL,
				billing_address_1 VARCHAR(190) NULL,
				billing_address_2 VARCHAR(190) NULL,
				billing_city VARCHAR(100) NULL,
				billing_state VARCHAR(100) NULL,
				billing_postcode VARCHAR(20) NULL,
				billing_country CHAR(2) NULL,
				tax_exempt TINYINT NOT NULL DEFAULT 0,
				status VARCHAR(32) NOT NULL DEFAULT 'active',
				deleted_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY email (email),
				KEY user_id (user_id),
				KEY status (status)
			) {$omnify_charset};",
			'customer_notes' => "CREATE TABLE {$this->table('customer_notes')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				customer_id BIGINT UNSIGNED NOT NULL,
				author_id BIGINT UNSIGNED NULL,
				customer_visible TINYINT NOT NULL DEFAULT 0,
				note LONGTEXT NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY customer_id (customer_id),
				KEY author_id (author_id),
				KEY customer_visible (customer_visible)
			) {$omnify_charset};",
			'customer_activity' => "CREATE TABLE {$this->table('customer_activity')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				customer_id BIGINT UNSIGNED NOT NULL,
				actor_id BIGINT UNSIGNED NULL,
				activity_type VARCHAR(80) NOT NULL,
				description TEXT NOT NULL,
				metadata LONGTEXT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY customer_id (customer_id),
				KEY activity_type (activity_type)
			) {$omnify_charset};",
			'downloads' => "CREATE TABLE {$this->table('downloads')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				file_id BIGINT UNSIGNED NOT NULL,
				customer_id BIGINT UNSIGNED NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'delivered',
				ip_address VARCHAR(64) NULL,
				user_agent TEXT NULL,
				downloaded_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY file_id (file_id),
				KEY customer_id (customer_id),
				KEY downloaded_at (downloaded_at)
			) {$omnify_charset};",
			'email_logs' => "CREATE TABLE {$this->table('email_logs')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				trigger_name VARCHAR(100) NOT NULL,
				recipient TEXT NOT NULL,
				subject TEXT NOT NULL,
				body LONGTEXT NULL,
				headers TEXT NULL,
				status VARCHAR(20) NOT NULL DEFAULT 'pending',
				error_message TEXT NULL,
				order_id BIGINT UNSIGNED NULL,
				context LONGTEXT NULL,
				created_at DATETIME NOT NULL,
				sent_at DATETIME NULL,
				PRIMARY KEY (id),
				KEY status (status),
				KEY trigger_name (trigger_name),
				KEY order_id (order_id),
				KEY created_at (created_at)
			) {$omnify_charset};",
			'customer_access' => "CREATE TABLE {$this->table('customer_access')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				customer_id BIGINT UNSIGNED NOT NULL,
				product_id BIGINT UNSIGNED NOT NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'active',
				expires_at DATETIME NULL,
				granted_by BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY customer_product (customer_id, product_id),
				KEY product_id (product_id),
				KEY status (status),
				KEY expires_at (expires_at)
			) {$omnify_charset};",
			'orders'     => "CREATE TABLE {$this->table('orders')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				customer_id BIGINT UNSIGNED NULL,
				product_id BIGINT UNSIGNED NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'pending',
				currency CHAR(3) NOT NULL DEFAULT 'USD',
				subtotal DECIMAL(18,6) NOT NULL DEFAULT 0,
				tax DECIMAL(18,6) NOT NULL DEFAULT 0,
				tax_label VARCHAR(80) NULL,
				tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
				tax_reporting_code VARCHAR(120) NULL,
				tax_inclusive TINYINT NOT NULL DEFAULT 0,
				tax_shipping TINYINT NOT NULL DEFAULT 0,
				customer_tax_exempt TINYINT NOT NULL DEFAULT 0,
				shipping_total DECIMAL(18,6) NOT NULL DEFAULT 0,
				shipping_method VARCHAR(160) NULL,
				total DECIMAL(18,6) NOT NULL DEFAULT 0,
				refunded_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
				coupon_code VARCHAR(80) NULL,
				discount_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
				payment_method VARCHAR(80) NULL,
				payment_instructions TEXT NULL,
				shipping_first_name VARCHAR(100) NULL,
				shipping_last_name VARCHAR(100) NULL,
				shipping_address_1 VARCHAR(190) NULL,
				shipping_address_2 VARCHAR(190) NULL,
				shipping_city VARCHAR(100) NULL,
				shipping_state VARCHAR(100) NULL,
				shipping_postcode VARCHAR(20) NULL,
				shipping_country VARCHAR(100) NULL,
				shipping_phone VARCHAR(60) NULL,
				billing_first_name VARCHAR(100) NULL,
				billing_last_name VARCHAR(100) NULL,
				billing_company VARCHAR(160) NULL,
				billing_phone VARCHAR(60) NULL,
				billing_address_1 VARCHAR(190) NULL,
				billing_address_2 VARCHAR(190) NULL,
				billing_city VARCHAR(100) NULL,
				billing_state VARCHAR(100) NULL,
				billing_postcode VARCHAR(20) NULL,
				billing_country VARCHAR(100) NULL,
				billing_same_as_shipping TINYINT NOT NULL DEFAULT 1,
				transaction_id VARCHAR(190) NULL,
				order_number VARCHAR(100) NULL,
				fulfillment_status VARCHAR(32) NOT NULL DEFAULT 'none',
				tracking_number VARCHAR(100) NULL,
				tracking_carrier VARCHAR(100) NULL,
				fraud_status VARCHAR(32) NOT NULL DEFAULT 'safe',
				fraud_score INT NOT NULL DEFAULT 0,
				fraud_flags TEXT NULL,
				ip_address VARCHAR(45) NULL,
				deleted_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY customer_status (customer_id, status),
				KEY product_id (product_id),
				UNIQUE KEY order_number (order_number)
			) {$omnify_charset};",
			'order_items' => "CREATE TABLE {$this->table('order_items')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				order_id BIGINT UNSIGNED NOT NULL,
				product_id BIGINT UNSIGNED NOT NULL,
				variation_id BIGINT UNSIGNED NULL DEFAULT NULL,
				product_name VARCHAR(190) NOT NULL,
				price DECIMAL(18,6) NOT NULL DEFAULT 0,
				tax DECIMAL(18,6) NOT NULL DEFAULT 0,
				quantity INT NOT NULL DEFAULT 1,
				refunded_qty INT NOT NULL DEFAULT 0,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY order_id (order_id),
				KEY product_id (product_id),
				KEY order_product (order_id, product_id)
			) {$omnify_charset};",
			'order_notes' => "CREATE TABLE {$this->table('order_notes')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				order_id BIGINT UNSIGNED NOT NULL,
				author_id BIGINT UNSIGNED NULL,
				note_type VARCHAR(32) NOT NULL DEFAULT 'private',
				customer_visible TINYINT NOT NULL DEFAULT 0,
				note LONGTEXT NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY order_id (order_id),
				KEY author_id (author_id),
				KEY customer_visible (customer_visible),
				KEY note_type (note_type)
			) {$omnify_charset};",
			'abandoned_carts' => "CREATE TABLE {$this->table('abandoned_carts')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				token VARCHAR(100) NOT NULL,
				email VARCHAR(190) NOT NULL DEFAULT '',
				first_name VARCHAR(100) NULL,
				last_name VARCHAR(100) NULL,
				phone VARCHAR(60) NULL,
				product_id BIGINT UNSIGNED NULL,
				variation_id BIGINT UNSIGNED NULL,
				quantity INT NOT NULL DEFAULT 1,
				cart_payload LONGTEXT NULL,
				subtotal DECIMAL(18,6) NOT NULL DEFAULT 0,
				currency CHAR(3) NOT NULL DEFAULT 'USD',
				coupon_code VARCHAR(80) NULL,
				checkout_url TEXT NULL,
				recovery_url TEXT NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'active',
				deleted_at DATETIME NULL,
				reminder_count INT UNSIGNED NOT NULL DEFAULT 0,
				last_reminder_at DATETIME NULL,
				recovered_order_id BIGINT UNSIGNED NULL,
				recovered_at DATETIME NULL,
				expires_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY token (token),
				KEY email_status (email(100), status),
				KEY status_updated (status, updated_at),
				KEY recovered_order_id (recovered_order_id)
			) {$omnify_charset};",
			'wishlists' => "CREATE TABLE {$this->table('wishlists')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				user_id BIGINT UNSIGNED NOT NULL,
				product_id BIGINT UNSIGNED NOT NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY user_product (user_id, product_id),
				KEY user_id (user_id),
				KEY product_id (product_id)
			) {$omnify_charset};",
			'coupons'     => "CREATE TABLE {$this->table('coupons')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
					code VARCHAR(80) NOT NULL,
					is_active TINYINT NOT NULL DEFAULT 1,
					discount_type VARCHAR(32) NOT NULL DEFAULT 'fixed',
					discount_value DECIMAL(18,6) NOT NULL DEFAULT 0,
					min_order_amount DECIMAL(18,6) NULL DEFAULT NULL,
					max_discount_amount DECIMAL(18,6) NULL DEFAULT NULL,
					usage_limit INT NULL,
					usage_limit_per_customer INT NULL,
					usage_count INT NOT NULL DEFAULT 0,
					free_shipping TINYINT NOT NULL DEFAULT 0,
					first_order_only TINYINT NOT NULL DEFAULT 0,
					included_product_ids TEXT NULL,
					excluded_product_ids TEXT NULL,
					included_categories TEXT NULL,
					excluded_categories TEXT NULL,
					expires_at DATETIME NULL,
					deleted_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY code (code)
			) {$omnify_charset};",
			'reviews'     => "CREATE TABLE {$this->table('reviews')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				customer_name VARCHAR(120) NOT NULL,
				customer_email VARCHAR(190) NOT NULL,
				rating TINYINT UNSIGNED NOT NULL,
				review_title VARCHAR(190) NOT NULL,
				review_content TEXT NOT NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'pending',
				deleted_at DATETIME NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY status (status)
			) {$omnify_charset};",
			'webhook_events' => "CREATE TABLE {$this->table('webhook_events')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				event_id VARCHAR(190) NOT NULL,
				gateway VARCHAR(50) NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY event_gateway (event_id, gateway)
			) {$omnify_charset};",
			'inventory_logs' => "CREATE TABLE {$this->table('inventory_logs')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				product_id BIGINT UNSIGNED NOT NULL,
				variation_id BIGINT UNSIGNED NULL,
				change_qty INT NOT NULL,
				new_qty INT NOT NULL,
				reason VARCHAR(255) NOT NULL,
				user_id BIGINT UNSIGNED NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY product_id (product_id),
				KEY variation_id (variation_id)
			) {$omnify_charset};",
			'admin_activities' => "CREATE TABLE {$this->table('admin_activities')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				user_id BIGINT UNSIGNED NOT NULL,
				action VARCHAR(100) NOT NULL,
				object_type VARCHAR(50) NOT NULL,
				object_id VARCHAR(100) NULL,
				description TEXT NOT NULL,
				ip_address VARCHAR(45) NULL,
				user_agent TEXT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY user_id (user_id),
				KEY action_object (action, object_type),
				KEY created_at (created_at)
			) {$omnify_charset};",
			'webhooks' => "CREATE TABLE {$this->table('webhooks')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				name VARCHAR(190) NOT NULL,
				url TEXT NOT NULL,
				secret VARCHAR(190) NOT NULL,
				events TEXT NOT NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'active',
				created_at DATETIME NOT NULL,
				updated_at DATETIME NOT NULL,
				PRIMARY KEY (id)
			) {$omnify_charset};",
			'webhook_delivery_logs' => "CREATE TABLE {$this->table('webhook_delivery_logs')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				webhook_id BIGINT UNSIGNED NOT NULL,
				event VARCHAR(100) NOT NULL,
				request_payload LONGTEXT NOT NULL,
				response_code INT NULL,
				response_body TEXT NULL,
				duration FLOAT NOT NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				KEY webhook_id (webhook_id)
			) {$omnify_charset};",
			'api_keys' => "CREATE TABLE {$this->table('api_keys')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				description VARCHAR(255) NOT NULL,
				consumer_key VARCHAR(100) NOT NULL,
				consumer_secret VARCHAR(100) NOT NULL,
				permissions VARCHAR(32) NOT NULL DEFAULT 'read',
				user_id BIGINT UNSIGNED NOT NULL,
				status VARCHAR(32) NOT NULL DEFAULT 'active',
				last_access DATETIME NULL,
				created_at DATETIME NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY consumer_key (consumer_key)
			) {$omnify_charset};",
			'metadata' => "CREATE TABLE {$this->table('metadata')} (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				object_type VARCHAR(50) NOT NULL,
				object_id BIGINT UNSIGNED NOT NULL,
				meta_key VARCHAR(190) NOT NULL,
				meta_value LONGTEXT NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY object_meta (object_type, object_id, meta_key),
				KEY meta_key (meta_key)
			) {$omnify_charset};",
		];
	}
}
